In [1]:
import pandas as pd
df = pd.read_table("chembl_24_1_chemreps.txt")
L = len(df)
print(L)
df.head()

1820035

,chembl_id,canonical_smiles,standard_inchi,standard_inchi_key
0,CHEMBL153534,Cc1cc(cn1C)c2csc(N=C(N)N)n2,InChI=1S/C10H13N5S/c1-6-3-7(4-15(6)2)8-5-16-10...,MFRNFCWYPYSFQQ-UHFFFAOYSA-N
1,CHEMBL440060,CC[C@H](C)[C@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...,InChI=1S/C123H212N44O34S/c1-19-63(12)96(164-11...,RSEQNZQKBMRQNM-VRGFNVLHSA-N
2,CHEMBL440245,CCCC[C@H](NC(=O)[C@H](CC(C)C)NC(=O)[C@H](CCCCN...,InChI=1S/C160H268N50O41/c1-23-27-41-95-134(228...,FTKBTEIKPOYCEX-OZSLQWTKSA-N
3,CHEMBL440249,CC(C)C[C@@H]1NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](N...,InChI=1S/C124H154ClN21O39/c1-57(2)48-81-112(17...,UYSXXKGACMHPIM-KFGDMSGDSA-N
4,CHEMBL405398,Brc1cccc(Nc2ncnc3ccncc23)c1NCCN4CCOCC4,InChI=1S/C19H21BrN6O/c20-15-2-1-3-17(18(15)22-...,VDSXZXJEWIWBCG-UHFFFAOYSA-N

In [2]:
smiles = df["canonical_smiles"].values
to_drop = []
for i, sm in enumerate(smiles):
    if len(sm) > 100:
        to_drop.append(i)
    if df['chembl_id'][i] == "CHEMBL1201364":
        to_drop.append(i)
print(len(to_drop))

97738

In [3]:
df_drop = df.drop(to_drop)
df_drop.to_csv("data/chembl_24.csv", index=False)

In [4]:
df_drop.head()

,chembl_id,canonical_smiles,standard_inchi,standard_inchi_key
0,CHEMBL153534,Cc1cc(cn1C)c2csc(N=C(N)N)n2,InChI=1S/C10H13N5S/c1-6-3-7(4-15(6)2)8-5-16-10...,MFRNFCWYPYSFQQ-UHFFFAOYSA-N
4,CHEMBL405398,Brc1cccc(Nc2ncnc3ccncc23)c1NCCN4CCOCC4,InChI=1S/C19H21BrN6O/c20-15-2-1-3-17(18(15)22-...,VDSXZXJEWIWBCG-UHFFFAOYSA-N
5,CHEMBL503634,COc1c(O)cc(O)c(C(=N)Cc2ccc(O)cc2)c1O,InChI=1S/C15H15NO5/c1-21-15-12(19)7-11(18)13(1...,OPELSESCRGGKAM-UHFFFAOYSA-N
6,CHEMBL503643,CCOC(=O)c1cc2cc(ccc2[nH]1)C(=O)O,InChI=1S/C12H11NO4/c1-2-17-12(16)10-6-8-5-7(11...,CAVYPAYXEMVXMS-UHFFFAOYSA-N
8,CHEMBL503870,C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C)C(=O)NN...,InChI=1S/C30H34N6O9/c1-20(33-30(42)45-19-22-8-...,QXUSQBUGZMVOOW-TVTVEFKISA-N

In [5]:
df_sol = pd.read_csv('data/datasets/freesolv/freesolv.csv')
df_sol.head()

                   smiles  freesolv
0  CN(C)C(=O)c1ccc(cc1)OC    -11.01
1            CS(=O)(=O)Cl     -4.87
2                CC(C)C=C      1.83
3              CCc1cnccn1     -5.45
4                CCCCCCCO     -4.21

In [7]:
smiles = df_sol['smiles'].values
pro_sms = []
for sm in smiles:
    sm = ' '.join(list(sm))
    before = ['C l -', 'C l', 'O -', 'N +', 'n +', 'B r -', 'B r', 'N a +', 'N a', 'I -', 'S i']
    after = ['Cl-', 'Cl', 'O-', 'N+', 'n+', 'Br-', 'Br', 'Na+', 'Na', 'I-', 'Si']
    for b,a in zip(before, after):
        sm = sm.replace(b, a)
    pro_sms.append(sm)

df_sol['processed_smiles'] = pro_sms
df_sol.head()

,smiles,freesolv,processed_smiles
0,CN(C)C(=O)c1ccc(cc1)OC,-11.01,C N ( C ) C ( = O ) c 1 c c c ( c c 1 ) O C
1,CS(=O)(=O)Cl,-4.87,C S ( = O ) ( = O ) Cl
2,CC(C)C=C,1.83,C C ( C ) C = C
3,CCc1cnccn1,-5.45,C C c 1 c n c c n 1
4,CCCCCCCO,-4.21,C C C C C C C O

In [8]:
df_sol.to_csv('data/solubility.csv')

In [9]:
df_sol = pd.read_csv('data/solubility.csv')
df_sol.head()

,Unnamed: 0,smiles,freesolv,processed_smiles
0,0,CN(C)C(=O)c1ccc(cc1)OC,-11.01,C N ( C ) C ( = O ) c 1 c c c ( c c 1 ) O C
1,1,CS(=O)(=O)Cl,-4.87,C S ( = O ) ( = O ) Cl
2,2,CC(C)C=C,1.83,C C ( C ) C = C
3,3,CCc1cnccn1,-5.45,C C c 1 c n c c n 1
4,4,CCCCCCCO,-4.21,C C C C C C C O